let LAW_VOCABULARY_OBJECT_ARRY = [
    { word: 'Acceptance', meaning: 'قبولیت' },
    { word: 'Affidavit', meaning: 'بیان حلفی' },
    { word: 'Aggrieved party', meaning: 'متاثرہ فریق' },
    { word: 'Agreement to Sell', meaning: 'اقرار نامہ' },
    { word: 'Alleged', meaning: 'مبينہ' },
    { word: 'Amendment', meaning: 'ترميم' },
    { word: 'Amicus curiae', meaning: 'عدالتی معاون' },
    { word: 'Anti-Terrorist', meaning: 'اِنسدادِ دہشت گردی' },
    { word: 'Applicant', meaning: 'سائل' },
    { word: 'Arrears of land revenue', meaning: 'بقایاجات مالیہ' },
    { word: 'Arbitration Council', meaning: 'ثالثی کونسل' },
    { word: 'Attachment/Distraint/Seizure of property in order to obtain payment', meaning: 'قرقی' },
    { word: 'Family Law/matrimonial law', meaning: 'عائلی قوانین' },
    { word: 'Farmer ID (Holding slips)', meaning: 'ختونی' },
    { word: 'Federal Shariat Court', meaning: 'وفاقی شرعی عدالت' },
    { word: 'Federation of Pakistan', meaning: 'وفاق پاکستان' },
    { word: 'Fiduciary relationship', meaning: 'نگہبانی تعلق/امانتی' },
    { word: 'FIR', meaning: 'ابتدائ اطلائ رپورٹ' },
    { word: 'Freedom of expression', meaning: 'اظہار رائےکی آزادی' },
    { word: 'Freedom of movement', meaning: 'نقل و حرکت کی آزادی' },
    { word: 'Fundamental rights', meaning: 'بنيادی حقوق' },
    { word: 'Cancellation', meaning: 'منسوخی' },
    { word: 'Cancellation/revocation of Power of attorney', meaning: 'اِبطال نامہ' },
    { word: 'Case diaries', meaning: 'ضمنی' },
    { word: 'Cause of action', meaning: 'بناۓ دعوی/ بناۓ نالش' },
    { word: 'Cause List', meaning: 'فہرست پیشی' },
    { word: 'Certified copy', meaning: 'مصدقہ نقل' },
    { word: 'Charge (criminal law)', meaning: 'فرد جرم' },
    { word: 'Circumstantial Evidence', meaning: 'قرائنی شہادت' },
    { word: 'Civil', meaning: 'ديوانی' },
    { word: 'Civil Miscellaneous', meaning: 'دیوانی متفرق' },
    { word: 'Code of Civil Procedure', meaning: 'مجموع ضابطہ ديوانی' },
    { word: 'Cognizable Offence', meaning: 'قابلِ دست اندازی' },
    { word: 'Competition Law', meaning: 'مسابقتی قانون' },
    { word: 'Complaint', meaning: 'استغاثہ' },
    { word: 'Complainant', meaning: 'مستغيث' },
    { word: 'Compromise deed', meaning: 'راضی نامہ' },
    { word: 'Compensation for hurt', meaning: 'عرش' },
    { word: 'Confession', meaning: 'اقبالِ جرم' },
    { word: 'Conflict of Interest', meaning: 'مفاداتی تصادم' },
    { word: 'Consolidation', meaning: 'اشتمال' },
    { word: 'Contract', meaning: 'معاہدہ' },
    { word: 'Correspondence', meaning: 'مراسلہ' },
    { word: 'Criminal Breach of Trust', meaning: 'خیانت مجرمانہ' },
    { word: 'Criminal Procedure Code', meaning: 'مجموع ضابطہ فوجداری' },
    { word: 'Cross Examination', meaning: 'جرح' },
    { word: 'Competent authority', meaning: 'مجاز اتھارٹی' },
    { word: 'Conditional Judgment', meaning: 'مشروط فیصلہ' },
    { word: 'Contempt of Court', meaning: 'توہین عدالت' },
    { word: 'Confront/confronting a witness', meaning: 'تقابُل/ گواہ کو متقابل کرانا' },
    { word: 'Constitution', meaning: 'آئين/ دستور' },
    { word: 'Constitutional Democracy', meaning: 'دستوری جمہوریت' },
    { word: 'Criminal', meaning: 'فوجداری' },
    { word: 'Criminal Abetment', meaning: 'اعانتِ مجرمانہ' },
    { word: 'Criminal breach of trust', meaning: 'خیانتِ مجرمانہ' },
    { word: 'Criminal intimidation', meaning: 'تخویفِ مجرمانہ' },
    { word: 'Custody', meaning: 'حضانت/ تحویل' },
    { word: 'Earnest money', meaning: 'زر بیعانہ' },
    { word: 'Easement', meaning: 'حق آسائش' },
    { word: 'Environmental law', meaning: 'ماحولیاتی قانون' },
    { word: 'Estoppel', meaning: 'امر مانع تقریر مخالف' },
    { word: 'Exclusion clause', meaning: 'استثنائی شق' },
    { word: 'Execution', meaning: 'اجراء' },
    { word: 'Exempt', meaning: 'مستثنی' },
    { word: 'Ex parte', meaning: 'يکطرفہ' },
    { word: 'Ejectment', meaning: 'بےدخلی' },
    { word: 'Examination in chief', meaning: 'ابترائی بیان' },
    { word: 'Extrinsic Evidence', meaning: 'خارجی شہادت' },
    { word: 'Daily diary', meaning: 'روزنامچہ' },
    { word: 'Damages', meaning: 'ہرجانہ' },
    { word: 'Deceased', meaning: 'متوفی' },
    { word: 'Declaration', meaning: 'دعوی استقرارِ حق' },
    { word: 'Declaration of Legal heirship', meaning: 'وراثت نامہ' },
    { word: 'Deed writer', meaning: 'وثیقہ نویس' },
    { word: 'Defamation', meaning: 'ہتک عزت' },
    { word: 'Defection', meaning: 'انحراف' },
    { word: 'Defendant', meaning: 'مدعاعلیہ' },
    { word: 'Defendants', meaning: 'مدعاعليھم' },
    { word: 'Delimitation of constituencies', meaning: 'حلقہ ہائے انتخابی حد بندی' },
    { word: 'Discovery & inspection of documents', meaning: 'دستاویز کے انکشافات و معائنہ' },
    { word: 'Discriminatory laws', meaning: 'امتیازی قوانین' },
    { word: 'Discretion', meaning: 'صوابدید' },
    { word: 'Disputed', meaning: 'متدعويہ' },
    { word: 'Dissolution of marriage', meaning: 'تنسیخ نکاح' },
    { word: 'Divorce', meaning: 'طلاق' },
    { word: 'Delegated right of divorce', meaning: 'طلاق تفویض' },
    { word: 'Doctrine of Laches', meaning: 'نظریہ غفلت/ تاخیر' },
    { word: 'Doctrine of necessity', meaning: 'نظریہ ضرورت' },
    { word: 'Documentary evidence', meaning: 'دستاویزی شہادت' },
    { word: 'Dower', meaning: 'حق مھر' },
    { word: 'Deferred dower', meaning: 'مھر موجل' },
    { word: 'Prompt dower', meaning: 'مھر معجل' },
    { word: 'Customary dower', meaning: 'مھر مثل' },
    { word: 'Due process', meaning: 'واجب عمل' },
    { word: 'Duress', meaning: 'اکراہ' },
    { word: 'General Adjournment', meaning: 'عمومی التواء' },
    { word: 'Gift Deed', meaning: 'ھبہ نامہ' },
    { word: 'Guardianship', meaning: 'ولایت' },
    { word: 'Harvest Inspection Register', meaning: 'خسرہ گرداوری' },
    { word: 'Hostile witness', meaning: 'منحرف گواہ' },
    { word: 'High Court', meaning: 'عدالت عاليہ' },
    { word: 'High Treason', meaning: 'سنگین غداری' },
    { word: 'Hue & Cry Notice', meaning: 'اشتہارِ شوروغوغہ' },
    { word: 'Leading question', meaning: 'ہدایتی سوال' },
    { word: 'Lease', meaning: 'پٹہ' },
    { word: 'Legal Capacity', meaning: 'قانونی اہلیت' },
    { word: 'Letter of administration', meaning: 'پروانہ انصرام جائیداد' },
    { word: 'Limitation', meaning: 'معياد' },
    { word: 'List of Documents', meaning: 'فہرست دستاویز' },
    { word: 'List of Reliance', meaning: 'فہرست انحصار' },
    { word: 'Local Bodies', meaning: 'بلدیاتی' },
    { word: 'Jactitation of Marriage', meaning: 'تکزیب ِ نکاح' },
    { word: 'Judgment Debtor', meaning: 'مدیون ڈگری' },
    { word: 'Judicial activism', meaning: 'عرالتی فعالیت' },
    { word: 'Judicial restraint', meaning: 'عرالتی تحمل' },
    { word: 'Jurisdiction', meaning: 'دائرہ اختیار/سماعت' },
    { word: 'Territorial jurisdiction', meaning: 'علا قائی اختیارِ سماعت' },
    { word: 'Pecuniary jurisdiction', meaning: 'مالیاتی اختیارِ سماعت' },
    { word: 'Justice of peace', meaning: 'منصفِ امن' },
    { word: 'Matter of fact', meaning: 'امر متعلقہ واقع' },
    { word: 'Matter of law', meaning: 'امر متعلقہ قانون' },
    { word: 'Maintenance (eg wife/child)', meaning: 'نان و نفقہ' },
    { word: 'Medico legal Report', meaning: 'طبی رپورٹ' },
    { word: 'Memorandum of Address', meaning: 'فرد پتہ' },
    { word: 'Minor', meaning: 'نابالغ' },
    { word: 'Misappropriates', meaning: 'خوردبرد کرنا' },
    { word: 'Mortgage', meaning: 'رہن' },
    { word: 'Motive', meaning: 'وجہ عناد' },
    { word: 'Murder (intentional)', meaning: 'قتلِ عمد' },
    { word: 'Mutation', meaning: 'اِنتقال' },
    { word: 'Mutual Legal Assistance', meaning: 'باہمی قانونی معاونت' },
    { word: 'Oath', meaning: 'حلف' },
    { word: 'Objective Resolution', meaning: 'قراردادِ مقاصد' },
    { word: 'Offer', meaning: 'ایجاب' },
    { word: 'Option of puberty', meaning: 'حقِ خیار البلوغ' },
    { word: 'Order Sheet', meaning: 'حکم نامہ' },
    { word: 'Order of court to produce records', meaning: 'روبکار' },
    { word: 'Negotiable Instruments', meaning: 'دستاویز قابلِ بیع و شری' },
    { word: 'Non Prosecution', meaning: 'عدم پیروی' },
    { word: 'Pakistan Penal Code', meaning: 'مجموعہِ تعزیراتِ پاکستان' },
    { word: 'Pending', meaning: 'زیرِ التویٰ' },
    { word: 'Permanent Injunction', meaning: 'حکم امتناعی دوامی' },
    { word: 'Personal law', meaning: 'شخصی قانون' },
    { word: 'Petitioner/Applicant', meaning: 'سائل / درخواست گزار' },
    { word: 'Plaint', meaning: 'عرضی دعویٴ' },
    { word: 'Plaintiff', meaning: 'مرعی' },
    { word: 'Plaintiffs', meaning: 'مدعيان' },
    { word: 'Power of attorney', meaning: 'مختادنامہ' },
    { word: 'Prayer', meaning: 'استدعا' },
    { word: 'Preliminary Objections', meaning: 'عزرات ابتدائی' },
    { word: 'Preemption', meaning: 'شفع' },
    { word: 'Presiding Officer', meaning: 'افسر جلیس' },
    { word: 'Process Fee', meaning: 'فرد طلبانہ' },
    { word: 'Public at large', meaning: 'عوامالناس' },
    { word: 'Public interest', meaning: 'مفادِ عامہ' },
    { word: 'Public importance', meaning: 'قومی نوعیت/عوامی اہمیت' },
    { word: 'Rape', meaning: 'زنا بِالجبر' },
    { word: 'Record of Rights', meaning: 'فرد ملکیت/جمعبندی/مسل حقیقت/رجسٹر حقدارانِ زمین' },
    { word: 'Periodical record of rights', meaning: 'فرد ملکیت/جمعبندی/مسل حقیقت/رجسٹر حقدارانِ زمینمسل میعادی' },
    { word: 'Recovery Memo', meaning: 'فرد برآمدگی/مقبوضگی' },
    { word: 'Redemption', meaning: 'بازیابی' },
    { word: 'Relief', meaning: 'دادرسی' },
    { word: 'Relinquishment Deed', meaning: 'دستبرداری نامہ' },
    { word: 'Respondent (if Applicant or Petitioner)', meaning: 'جواب دہند گان' },
    { word: 'Respondents', meaning: 'مسؤل عليھم' },
    { word: 'Restitution of conjugal rights', meaning: 'اعادہ حقوقِ زن آشوئ/اعادہ حقوقِ زوجیت' },
    { word: 'Retribution', meaning: 'قِساس' },
    { word: 'Review', meaning: 'نظر ثانی' },
    { word: 'Revision', meaning: 'نگرانی' },
    { word: 'Rough crime scene sketch (plan)', meaning: 'نقشہ موقع' },
    { word: 'Ultra Vires', meaning: 'ماورائےاختیار/ ماورائےقانون' },
    { word: 'Under Objection', meaning: 'تابعِ عزر/زیرِ اعتراض' },
    { word: 'Sale Deed', meaning: 'معاہدہ بيع/بیع نامہ' },
    { word: 'Separation (marital)', meaning: 'علیحد گی' },
    { word: 'Short Order', meaning: 'مختصر حکم' },
    { word: 'Specific Performance', meaning: 'تعميل مختص' },
    { word: 'Specific Relief Act 1877', meaning: 'قانون دادرسی مختص مجریہ 1877' },
    { word: 'State', meaning: 'ریاست' },
    { word: 'Statement of informant', meaning: 'فرد بیان' },
    { word: 'Succession', meaning: 'جانشينی' },
    { word: 'Summon', meaning: 'طلبی' },
    { word: 'Supreme Court', meaning: 'عدالت عظمی' },
    { word: 'Suit', meaning: 'دعوی' },
    { word: 'Suo Motu', meaning: 'اَز خود' },
    { word: 'Surety', meaning: 'ضامن' },
    { word: 'Survey Number (Field register)', meaning: 'خسرہ نمبر/سرول نمبر' },
    { word: 'Transfer (moveable property)', meaning: 'محولہ مال' },
    { word: 'Tribunal', meaning: 'دیوانِ اختصاص' },
    { word: 'Trespass', meaning: 'استحكامِ حق' },
    { word: 'Trust Deed', meaning: 'ردی کتاب/وقف نامہ' },
    { word: 'Title of Suit', meaning: 'عنوانِ دعوی' },
    { word: 'Tort', meaning: 'فعل بےجا/زیاں/تضییع' },
    { word: 'Third Party', meaning: 'شخصِ سوم' },
    { word: 'Unclaimed Article', meaning: 'مالِ متروک' },
    { word: 'Undivided family', meaning: 'ہنسلہ شدہ خاندان' },
    { word: 'Uniform', meaning: 'یکسان' },
    { word: 'Unsound Mind', meaning: 'بے ہوشی' },
    { word: 'Vicarious liability', meaning: 'عہدی مسئولیت' },
    { word: 'Vicinage', meaning: 'پڑوس' },
    { word: 'Void', meaning: 'باطل' },
    { word: 'Voluntary Return', meaning: 'رجعت رضاکارانہ' },
    { word: 'Vouching in aid', meaning: 'ساتھی کی پشت پشت' },
    { word: 'Waiver', meaning: 'منکری' },
    { word: 'Warrant', meaning: 'حکم / پھٹوا' },
    { word: 'Warrant of arrest', meaning: 'پکڑنامہ' },
    { word: 'Warrant of possession', meaning: 'قبضہ نامہ' },
    { word: 'Witness', meaning: 'گواہ' },
    { word: 'Women Protection Bill', meaning: 'حمايتِ خواتين بل' },
    { word: 'Workmen Compensation', meaning: 'عمال کی تھیس پر معاونت' },
    { word: 'Written Statement', meaning: 'جواب دعوی/جوابی حکمت عملی' },
    { word: 'Zoning Laws', meaning: 'زون محددات' },
    { word: 'Tariff', meaning: 'نرخ' },
    { word: 'Temporary Injunction', meaning: 'حکم امتناعی عارضی' },
    { word: 'Trade marks', meaning: 'نشانات تجارت' },
    { word: 'Without Prejudice', meaning: 'بلا تعصب, کسی جانبداری کے بغیر' },
    { word: 'Writ petition', meaning: 'آئینی درخواست' },
    { word: 'Wrongful confinement', meaning: 'حبسِ بے جا' },
    { word: 'Valuation', meaning: 'قيمت تخمينہ/ مالیت دعوی' },
    { word: 'Verification', meaning: 'تصديق' },
    { word: 'Versus', meaning: 'بنام' },
    { word: 'Violence', meaning: 'تشدد' },
    { word: 'Voidable', meaning: 'قابلِ فسخ' }
  ];
  
export {LAW_VOCABULARY_OBJECT_ARRY};